/**
 * NLP configuration and constants
 * Adjust these values to tune chatbot behavior
 */

import { NLPConfig } from "./type";

// Core NLP settings
export const NLP_CONFIG: NLPConfig = {
  minConfidence: 0.3, // Minimum confidence threshold (0-1)
  tokenMinLength: 2, // Ignore tokens shorter than this
  synonymWeight: 0.8, // Weight for synonym matches vs exact matches
  exactMatchBonus: 0.5, // Bonus score for exact keyword match
  categoryMatchBonus: 0.2, // Bonus when following same category
};

// Stop words to filter out (common words with low semantic value)
export const STOP_WORDS: Record<string, string[]> = {
  id: [
    "adalah",
    "ada",
    "apa",
    "apakah",
    "atau",
    "dan",
    "di",
    "ini",
    "itu",
    "jadi",
    "jika",
    "kalau",
    "karena",
    "ke",
    "untuk",
    "yang",
    "saya",
    "kita",
    "dengan",
    "dari",
    "pada",
    "oleh",
    "akan",
    "telah",
    "sudah",
    "belum",
    "bisa",
    "dapat",
    "mau",
    "ingin",
  ],
  en: [
    "is",
    "are",
    "am",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "should",
    "could",
    "may",
    "might",
    "must",
    "can",
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "up",
    "about",
    "into",
    "through",
    "during",
    "i",
    "you",
    "we",
    "they",
    "it",
    "this",
    "that",
    "what",
    "which",
    "who",
    "when",
    "where",
    "why",
    "how",
  ],
};

// Character normalization map for better matching
export const CHAR_NORMALIZE_MAP: Record<string, string> = {
  á: "a",
  à: "a",
  â: "a",
  ä: "a",
  é: "e",
  è: "e",
  ê: "e",
  ë: "e",
  í: "i",
  ì: "i",
  î: "i",
  ï: "i",
  ó: "o",
  ò: "o",
  ô: "o",
  ö: "o",
  ú: "u",
  ù: "u",
  û: "u",
  ü: "u",
};
